CREATE TABLE `BOOKMARK` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `RUN_TIME` timestamp NULL DEFAULT NULL,
  `UPDATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TABLE_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)