CREATE TABLE `ELECTRICITY_PRODUCTION` (
  `COUNTRY_NAME` TEXT,
  `DATE` TEXT,
  `PARAMETER` TEXT,
  `PRODUCT` TEXT,
  `VALUE` DOUBLE DEFAULT NULL,
  `UNIT` TEXT,
  `CREATED_ON` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_ON` TIMESTAMP NULL DEFAULT NULL,
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
)