version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'pipeline_pool'              # name of database
      MYSQL_USER: 'hive'                # name of user
      MYSQL_PASSWORD: ''          # password for  user
      MYSQL_ROOT_PASSWORD: ''     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: